/// Flutter icons Rede_app
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RedeCustomIcons
///      fonts:
///       - asset: fonts/RedeCustomIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class RedeCustomIcons {
  RedeCustomIcons._();

  static const _kFontFam = 'RedeCustomIcons';

  static const IconData book = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData youtube_play = IconData(0xf16a, fontFamily: _kFontFam);
  static const IconData instagram_1 = IconData(0xf16d, fontFamily: _kFontFam);
}
